//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarketing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmarketingEntities : DbContext
    {
        public EmarketingEntities()
            : base("name=EmarketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tadmin> Tadmin { get; set; }
        public virtual DbSet<Tcategory> Tcategory { get; set; }
        public virtual DbSet<Tproduct> Tproduct { get; set; }
        public virtual DbSet<Tuser> Tuser { get; set; }
    }
}
