//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tproduct
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_image { get; set; }
        public Nullable<int> product_price { get; set; }
        public Nullable<int> product_fk_user { get; set; }
        public string product_des { get; set; }
        public Nullable<int> product_fk_category { get; set; }
    
        public virtual Tcategory Tcategory { get; set; }
        public virtual Tuser Tuser { get; set; }
    }
}
