//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuser()
        {
            this.Tproduct = new HashSet<Tproduct>();
        }
    
        public int Tuser_id { get; set; }
        public string Tuser_name { get; set; }
        public string Tuser_email { get; set; }
        public string Tuser_password { get; set; }
        public string Tuser_image { get; set; }
        public string Tuser_contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tproduct> Tproduct { get; set; }
    }
}
